### ISSUE TITLE
Testing functions with Puppet 4

### ISSUE THREAD

**Issue by bodgit** [mcanevet/rspec-puppet-facts#34]
I have the following rspec tests for my functions based on the example in the README:

``` ruby
require 'spec_helper'

describe 'my_function' do

  let(:scope) { PuppetlabsSpec::PuppetInternals.scope }

  on_supported_os.each do |os, facts|
    context "on #{os}" do
      before :each do
        facts.each do |k, v|
          scope.stubs(:lookupvar).with("::#{k}").returns(v)
          scope.stubs(:lookupvar).with(k.to_s).returns(v)
        end
      end
      it { should run.with_params(...).and_return(...) }
      ...
    end
  end
end
```

This all works fine on Puppet `~> 3.0` but as soon as I try with `~> 4.0` I get errors like this:

```
  x) my_function on centos-6-x86_64 
      Failure/Error: it { should run.with_params(...).and_return(...) }

      NameError:
        undefined method `function_my_function' for class `Puppet::Parser::Scope'
```

If I remove the `let(:scope) ...` and associated bits then it works again but obviously lacks the per-OS facts, etc. Is there some additional setup needed for Puppet 4?

**Comment by ghoneycutt** [comment]
Closing due to age. Please re-open if this is still an issue with Puppet 5 or 6.
